version: '2'

services:
  app:
    image: 'docker-spring-boot-mongo:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: 'mongo:latest'
    container_name: db